project:
  type: website
  resources:
    - assets/**

website:
  title: "Industrial Robotics and PLCs"
  favicon: favicon.ico

  repo-url: https://github.com/frdedynamics/Industrial-Robotics-and-PLCs
  repo-branch: master
  repo-actions: [edit, issue]

  sidebar:
    style: floating
    search: true
    contents: 
      - text: "Home"
        href: index.qmd

      - section: Robot Foundations
        contents: 
          - pages/robots.qmd
          - pages/robot_programming.qmd
          - pages/robot_safety.qmd
          - pages/frames_poses.qmd
          - pages/kinematics.qmd
          
      - section: Simulation
        contents: 
          - pages/simulation.qmd
          
      - text: "Further Reading"
        href: pages/further_reading.qmd

      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    embed-resources: false



execute:
  freeze: false
  cache: false
